// <auto-generated />
using System;
using CustomerInfo.Grpc.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerInfo.Grpc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerInfo.Grpc.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Địa chỉ chi tiết");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã bệnh nhân");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date")
                        .HasComment("Ngày sinh");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Quận/Huyện");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint")
                        .HasComment("Giới tính (0: Nữ, 1: Nam)");

                    b.Property<string>("IdentityCard")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("CMND/CCCD");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsForeigner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Có phải người nước ngoài hay không");

                    b.Property<bool>("IsPregnant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Có thai hay không");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Tên bệnh nhân");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Số điện thoại");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Tỉnh/Thành phố");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Phường/Xã");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_Code")
                        .HasFilter("\"IsSuspended\" = false AND \"IsCancelled\" = false");

                    b.HasIndex("IdentityCard")
                        .HasDatabaseName("IX_Patients_IdentityCard");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Patients_Name");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_Patients_PhoneNumber");

                    b.ToTable("Patients", "public", t =>
                        {
                            t.HasComment("Bảng thông tin bệnh nhân");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "123 Đường Nguyễn Huệ",
                            Code = "BN001",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1990, 5, 14, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận 1",
                            Email = "testpatient.01@gmail.com",
                            Gender = (short)1,
                            IdentityCard = "123456789",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Nguyễn Văn An",
                            PhoneNumber = "0987654321",
                            Province = "TP. Hồ Chí Minh",
                            Ward = "Phường Bến Nghé"
                        },
                        new
                        {
                            Id = 2,
                            AddressDetail = "456 Đường Lê Lợi",
                            Code = "BN002",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1985, 8, 19, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận 3",
                            Email = "testpatient.02@gmail.com",
                            Gender = (short)0,
                            IdentityCard = "234567890",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = true,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Trần Thị Bình",
                            PhoneNumber = "0987654322",
                            Province = "TP. Hồ Chí Minh",
                            Ward = "Phường 6"
                        },
                        new
                        {
                            Id = 3,
                            AddressDetail = "789 Đường Đồng Khởi",
                            Code = "BN003",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1995, 3, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Phường Linh Trung",
                            Email = "testpatient.03@gmail.com",
                            Gender = (short)1,
                            IdentityCard = "345678901",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Lê Văn Cường",
                            PhoneNumber = "0987654323",
                            Province = "TP. Thủ Đức",
                            Ward = "Phường Linh Trung"
                        },
                        new
                        {
                            Id = 4,
                            AddressDetail = "321 Đường Nguyễn Du",
                            Code = "BN004",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1988, 12, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận Hoàn Kiếm",
                            Email = "testpatient.04@gmail.com",
                            Gender = (short)0,
                            IdentityCard = "456789012",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Phạm Thị Dung",
                            PhoneNumber = "0987654324",
                            Province = "TP. Hà Nội",
                            Ward = "Phường Hàng Bạc"
                        },
                        new
                        {
                            Id = 5,
                            AddressDetail = "654 Đường Lê Duẩn",
                            Code = "BN005",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1980, 7, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận Hải Châu",
                            Email = "testpatient.05@gmail.com",
                            Gender = (short)1,
                            IdentityCard = "567890123",
                            IsCancelled = false,
                            IsForeigner = true,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "John Smith",
                            PhoneNumber = "0987654325",
                            Province = "TP. Đà Nẵng",
                            Ward = "Phường Thạch Thang"
                        },
                        new
                        {
                            Id = 6,
                            AddressDetail = "987 Đường Pasteur",
                            Code = "BN006",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1992, 4, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận Ninh Kiều",
                            Email = "testpatient.07@gmail.com",
                            Gender = (short)1,
                            IdentityCard = "678901234",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Hoàng Văn Minh",
                            PhoneNumber = "0987654326",
                            Province = "TP. Cần Thơ",
                            Ward = "Phường Xuân Khánh"
                        },
                        new
                        {
                            Id = 7,
                            AddressDetail = "147 Đường Võ Văn Tần",
                            Code = "BN007",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1993, 9, 29, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Quận Ngô Quyền",
                            Email = "testpatient.08@gmail.com",
                            Gender = (short)0,
                            IdentityCard = "789012345",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = true,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Nguyễn Thị Hương",
                            PhoneNumber = "0987654327",
                            Province = "TP. Hải Phòng",
                            Ward = "Phường Lạch Tray"
                        },
                        new
                        {
                            Id = 8,
                            AddressDetail = "258 Đường Nguyễn Đình Chiểu",
                            Code = "BN008",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1987, 6, 11, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "Phường Tân Hiệp",
                            Email = "testpatient.09@gmail.com",
                            Gender = (short)1,
                            IdentityCard = "890123456",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Trần Văn Phúc",
                            PhoneNumber = "0987654328",
                            Province = "TP. Biên Hòa",
                            Ward = "Phường Tân Hiệp"
                        },
                        new
                        {
                            Id = 9,
                            AddressDetail = "369 Đường Lý Tự Trọng",
                            Code = "BN009",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1991, 11, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "TP. Huế",
                            Email = "testpatient.10@gmail.com",
                            Gender = (short)0,
                            IdentityCard = "901234567",
                            IsCancelled = false,
                            IsForeigner = true,
                            IsPregnant = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Sarah Johnson",
                            PhoneNumber = "0987654329",
                            Province = "TP. Huế",
                            Ward = "Phường Phú Hội"
                        },
                        new
                        {
                            Id = 10,
                            AddressDetail = "741 Đường Đồng Khởi",
                            Code = "BN010",
                            CreatedAt = new DateTime(2023, 12, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 0,
                            DOB = new DateTime(1994, 2, 27, 17, 0, 0, 0, DateTimeKind.Utc),
                            District = "TP. Nha Trang",
                            Email = "testpatient.11@gmail.com",
                            Gender = (short)0,
                            IdentityCard = "012345678",
                            IsCancelled = false,
                            IsForeigner = false,
                            IsPregnant = true,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedBy = 0,
                            Name = "Lê Thị Mai",
                            PhoneNumber = "0987654330",
                            Province = "TP. Nha Trang",
                            Ward = "Phường Vĩnh Hòa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
