// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaccinationReception.Infrastructure.Data;

#nullable disable

namespace VaccinationReception.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618140729_AddTableVaccination")]
    partial class AddTableVaccination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VaccinationReception.Domain.Models.DiseaseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DiseaseGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Các bệnh có khả năng lây truyền từ người sang người",
                            GroupName = "Nhóm bệnh truyền nhiễm",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Các bệnh không có khả năng lây truyền",
                            GroupName = "Nhóm bệnh không truyền nhiễm",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.DiseaseGroupService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DiseaseGroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseGroupId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DiseaseGroupServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DiseaseGroupId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DiseaseGroupId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasComment("Mã bệnh nhân");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Ngày tiếp nhận");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasComment("Loại dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Receptions_PatientId");

                    b.HasIndex("ReceptionDate")
                        .HasDatabaseName("IX_Receptions_ReceptionDate");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Receptions", "public", t =>
                        {
                            t.HasComment("Bảng tiếp nhận bệnh nhân");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ReceptionVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Ngày hẹn tiêm");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasComment("Mã bác sĩ");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Ngày xuất hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("Đã xác nhận");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasComment("Đã thanh toán");

                    b.Property<bool>("IsReadyToUse")
                        .HasColumnType("boolean")
                        .HasComment("Sẵn sàng sử dụng");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Ghi chú");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Ngày dự kiến tiêm");

                    b.Property<string>("TestResultEntry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Kết quả thử");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasComment("Mã vắc xin");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .HasDatabaseName("IX_ReceptionVaccinations_ReceptionId");

                    b.HasIndex("VaccineId")
                        .HasDatabaseName("IX_ReceptionVaccinations_VaccineId");

                    b.ToTable("ReceptionVaccinations", "public", t =>
                        {
                            t.HasComment("Bảng chỉ định tiêm chủng");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.RequestForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo phiếu");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo phiếu");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasComment("Số phiếu yêu cầu");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .HasDatabaseName("IX_RequestForms_ReceptionId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_RequestForms_RequestNumber");

                    b.ToTable("RequestForms", "public", t =>
                        {
                            t.HasComment("Bảng phiếu yêu cầu dịch vụ");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ScreeningEvaluationReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Khóa chính")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("integer")
                        .HasComment("Huyết áp tâm trương");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("integer")
                        .HasComment("Huyết áp tâm thu");

                    b.Property<double>("BodyTemperatureC")
                        .HasColumnType("double precision")
                        .HasComment("Nhiệt độ cơ thể (°C)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo");

                    b.Property<bool>("HasAbnormalHeartSound")
                        .HasColumnType("boolean")
                        .HasComment("Nghe tim bất thường");

                    b.Property<bool>("HasAbnormalTemperatureOrVitals")
                        .HasColumnType("boolean")
                        .HasComment("Nhiệt độ/sinh hiệu bất thường");

                    b.Property<bool>("HasAcuteOrChronicDisease")
                        .HasColumnType("boolean")
                        .HasComment("Bệnh cấp/mạn tính");

                    b.Property<bool>("HasHeartValveDisorder")
                        .HasColumnType("boolean")
                        .HasComment("Rối loạn van tim");

                    b.Property<bool>("HasNeurologicalAbnormalities")
                        .HasColumnType("boolean")
                        .HasComment("Bất thường thần kinh");

                    b.Property<bool>("HasOtherContraindications")
                        .HasColumnType("boolean")
                        .HasComment("Chống chỉ định khác");

                    b.Property<bool>("HasSevereFeverAfterPreviousVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Sốt nặng sau tiêm trước");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsContraindicatedForVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Chống chỉ định");

                    b.Property<bool>("IsEligibleForVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Đủ điều kiện tiêm");

                    b.Property<bool>("IsOnOrRecentlyEndedCorticosteroids")
                        .HasColumnType("boolean")
                        .HasComment("Đang/đã dùng corticosteroid");

                    b.Property<bool>("IsReferredToHospital")
                        .HasColumnType("boolean")
                        .HasComment("Chuyển viện");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<bool>("IsUnderweightBelow2000g")
                        .HasColumnType("boolean")
                        .HasComment("Thiếu cân < 2000g");

                    b.Property<bool>("IsVaccinationDeferred")
                        .HasColumnType("boolean")
                        .HasComment("Tạm hoãn");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật");

                    b.Property<string>("ParentFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Họ tên phụ huynh");

                    b.Property<string>("ParentPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Số điện thoại phụ huynh");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Khóa ngoại đến bảng tiếp nhận");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision")
                        .HasComment("Cân nặng (kg)");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ScreeningEvaluationReports_ReceptionId");

                    b.ToTable("ScreeningEvaluationReports", "public", t =>
                        {
                            t.HasComment("Bảng ghi nhận đánh giá sàng lọc trước tiêm");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DepartmentId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceCode = "VAC001",
                            ServiceName = "Tiêm vắc xin 5 trong 1",
                            UnitPrice = 500000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DepartmentId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceCode = "VAC002",
                            ServiceName = "Tiêm vắc xin 6 trong 1",
                            UnitPrice = 600000m
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServiceGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            GroupName = "Nhóm dịch vụ tiêm chủng cơ bản",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            GroupName = "Nhóm dịch vụ tiêm chủng đặc biệt",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceGroupService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceGroupServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceGroupId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceGroupId = 2,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("Ngày xuất hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasComment("Đã thanh toán");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng");

                    b.Property<int>("RequestFormId")
                        .HasColumnType("integer")
                        .HasComment("Mã phiếu yêu cầu");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasComment("Mã dịch vụ");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá");

                    b.HasKey("Id");

                    b.HasIndex("RequestFormId")
                        .HasDatabaseName("IX_ServiceRequestDetails_RequestFormId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServiceRequestDetails_ServiceId");

                    b.ToTable("ServiceRequestDetails", "public", t =>
                        {
                            t.HasComment("Bảng chi tiết yêu cầu dịch vụ");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã loại dịch vụ");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Tên loại dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceTypes_Code");

                    b.ToTable("ServiceTypes", "public", t =>
                        {
                            t.HasComment("Loại hình dịch vụ tiếp nhận");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VAC001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            Name = "Tiêm chủng dịch vụ"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VAC002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            Name = "Tiêm chủng đặc biệt"
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExaminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExaminationResult")
                        .HasColumnType("text");

                    b.Property<bool>("HasFeverAbove39")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasInjectionSiteReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOtherReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("ObservationConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherReactionDescription")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PostVaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostVaccinationResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceptionVaccinationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduleVaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaccinationConfirmation")
                        .HasColumnType("text");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionVaccinationId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.DiseaseGroupService", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.DiseaseGroup", "DiseaseGroup")
                        .WithMany("DiseaseGroupServices")
                        .HasForeignKey("DiseaseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiseaseGroup");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.ServiceType", "ServiceType")
                        .WithMany("Receptions")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ReceptionVaccination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany("ReceptionVaccinations")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.RequestForm", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany("RequestForms")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ScreeningEvaluationReport", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithOne("ScreeningEvaluationReport")
                        .HasForeignKey("VaccinationReception.Domain.Models.ScreeningEvaluationReport", "ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceGroupService", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.ServiceGroup", "ServiceGroup")
                        .WithMany("ServiceGroupServices")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.Service", "Service")
                        .WithMany("ServiceGroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceRequestDetail", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.RequestForm", "RequestForm")
                        .WithMany("ServiceRequestDetails")
                        .HasForeignKey("RequestFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.Service", "Service")
                        .WithMany("ServiceRequestDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestForm");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Vaccination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.ReceptionVaccination", "ReceptionVaccination")
                        .WithMany()
                        .HasForeignKey("ReceptionVaccinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceptionVaccination");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.DiseaseGroup", b =>
                {
                    b.Navigation("DiseaseGroupServices");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.Navigation("ReceptionVaccinations");

                    b.Navigation("RequestForms");

                    b.Navigation("ScreeningEvaluationReport");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.RequestForm", b =>
                {
                    b.Navigation("ServiceRequestDetails");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Service", b =>
                {
                    b.Navigation("ServiceGroupServices");

                    b.Navigation("ServiceRequestDetails");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceGroup", b =>
                {
                    b.Navigation("ServiceGroupServices");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceType", b =>
                {
                    b.Navigation("Receptions");
                });
#pragma warning restore 612, 618
        }
    }
}
