// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaccinationReception.Infrastructure.Data;

#nullable disable

namespace VaccinationReception.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250813141156_UpdateReceptionForClosingWithIssue")]
    partial class UpdateReceptionForClosingWithIssue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VaccinationReception.Domain.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá trị thực tế");

                    b.Property<decimal?>("AdvanceAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá trị tạm ứng");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Tên công ty ký kết");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã hợp đồng");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày ký hợp đồng");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Tên hợp đồng");

                    b.Property<int>("ContractNumber")
                        .HasColumnType("integer")
                        .HasComment("Số hợp đồng");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá trị hợp đồng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Diễn giải nội dung");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày dự kiến tiêm theo kế hoạch");

                    b.Property<int>("ExpectedPatientCount")
                        .HasColumnType("integer")
                        .HasComment("Số lượng bệnh nhân dự kiến");

                    b.Property<int>("ExpectedVaccineCount")
                        .HasColumnType("integer")
                        .HasComment("Số lượng vaccine dự kiến");

                    b.Property<Guid?>("FileContractId")
                        .HasColumnType("uuid")
                        .HasComment("File hợp đồng id");

                    b.Property<string>("FileContractName")
                        .HasColumnType("text")
                        .HasComment("File hợp đồng");

                    b.Property<Guid?>("FileVaccinationEnrollmentId")
                        .HasColumnType("uuid")
                        .HasComment("File excel đăng ký vacicnation id");

                    b.Property<string>("FileVaccinationEnrollmentName")
                        .HasColumnType("text")
                        .HasComment("File excel đăng ký vacicnation");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái hợp đồng");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Tên đơn vị trực thuộc công ty");

                    b.HasKey("Id");

                    b.ToTable("Contracts", "public", t =>
                        {
                            t.HasComment("Hợp đồng");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ContractPatientVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("integer")
                        .HasComment("Mã hợp đồng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("integer");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("integer")
                        .HasComment("Liều số mấy");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasComment("Mã bệnh nhân");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceptionVaccinationId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiêm chủng thực tế");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái của mũi tiêm kế hoạch");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasComment("Mã vắc xin");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ReceptionVaccinationId")
                        .IsUnique();

                    b.ToTable("ContractPatientVaccinations", "public", t =>
                        {
                            t.HasComment("Kế hoạch tiêm chủng của bệnh nhân theo hợp đồng");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ContractServiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualTotalAmount")
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer")
                        .HasComment("Mã hợp đồng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng thực tế");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasComment("Mã dịch vụ");

                    b.Property<decimal?>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Tổng tiền thực tế cho mục này");

                    b.Property<decimal?>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá của dịch vụ/vắc-xin này theo hợp đồng");

                    b.Property<int?>("VaccineId")
                        .HasColumnType("integer")
                        .HasComment("Mã vắc-xin");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractServiceDetails", "public", t =>
                        {
                            t.HasComment("Chi tiết dịch vụ/vắc-xin trong hợp đồng");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnose")
                        .HasColumnType("text");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("PerformTechnicianId")
                        .HasColumnType("integer");

                    b.Property<string>("PerformTechnicianName")
                        .HasColumnType("text");

                    b.Property<int?>("ReceptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceptionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SampleQuality")
                        .HasColumnType("integer");

                    b.Property<int?>("SampleType")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ExaminationTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ExaminationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<string>("ResultValue")
                        .HasColumnType("text");

                    b.Property<string>("StandardValue")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationId");

                    b.ToTable("ExaminationTestResults");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATMTransactionCode")
                        .HasColumnType("text")
                        .HasComment("Mã giao dịch ATM");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasComment("Số hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Cash")
                        .HasComment("Phương thức thanh toán");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasComment("Ghi chú");

                    b.Property<int?>("OriginalPaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Receipt")
                        .HasComment("Loại thanh toán");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasComment("Trạng thái thanh toán");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Tổng số tiền");

                    b.HasKey("Id");

                    b.HasIndex("OriginalPaymentId");

                    b.HasIndex("ReceptionId")
                        .HasDatabaseName("IX_Payments_ReceptionId");

                    b.ToTable("Payments", "public", t =>
                        {
                            t.HasComment("Bảng thanh toán");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.PaymentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ATMCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã giao dịch thẻ ATM");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer")
                        .HasComment("Hop Dong Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasComment("Người lập hóa đơn");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Số hóa đơn");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("integer")
                        .HasComment("Loại hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Tên đơn vị thanh toán");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasComment("Hình thức thanh toán");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasComment("Trạng thái thanh toán");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Mã số thuế đơn vị");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Giá trị hợp đồng");

                    b.Property<string>("VATInvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Số HĐ GTGT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("PaymentContracts", "public", t =>
                        {
                            t.HasComment("Hợp đồng thanh toán");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.PaymentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Số tiền");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer")
                        .HasComment("Mã thanh toán");

                    b.Property<int?>("ReceptionVaccinationId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiêm chủng");

                    b.Property<int?>("ServiceRequestDetailId")
                        .HasColumnType("integer")
                        .HasComment("Mã chi tiết yêu cầu dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_PaymentDetails_PaymentId");

                    b.HasIndex("ReceptionVaccinationId");

                    b.HasIndex("ServiceRequestDetailId");

                    b.ToTable("PaymentDetails", "public", t =>
                        {
                            t.HasComment("Chi tiết thanh toán");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("integer")
                        .HasComment("Mã hợp đồng");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<bool>("IsVaccinationTodayConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssueNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasComment("Mã bệnh nhân");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tiếp nhận");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasComment("Loại dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Receptions_PatientId");

                    b.HasIndex("ReceptionDate")
                        .HasDatabaseName("IX_Receptions_ReceptionDate");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Receptions", "public", t =>
                        {
                            t.HasComment("Bảng tiếp nhận bệnh nhân");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ReceptionVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày hẹn tiêm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasComment("Mã bác sĩ");

                    b.Property<int?>("DoseNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày xuất hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsPreExaminationTesting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadyToUse")
                        .HasColumnType("boolean")
                        .HasComment("Sẵn sàng sử dụng");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssueNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Ghi chú");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NotPaid")
                        .HasComment("Trạng thái thanh toán");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasComment("Số phiếu yêu cầu");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày dự kiến tiêm");

                    b.Property<int?>("SecondaryReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận phụ (nếu tiêm ở lần khác)");

                    b.Property<string>("TestResultEntry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Kết quả thử");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá");

                    b.Property<DateTime?>("VaccinationTestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasComment("Mã vắc xin");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .HasDatabaseName("IX_ReceptionVaccinations_ReceptionId");

                    b.HasIndex("SecondaryReceptionId");

                    b.HasIndex("VaccineId")
                        .HasDatabaseName("IX_ReceptionVaccinations_VaccineId");

                    b.ToTable("ReceptionVaccinations", "public", t =>
                        {
                            t.HasComment("Bảng chỉ định tiêm chủng");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ScreeningEvaluationReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Khóa chính")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("integer")
                        .HasComment("Huyết áp tâm trương");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("integer")
                        .HasComment("Huyết áp tâm thu");

                    b.Property<double>("BodyTemperatureC")
                        .HasColumnType("double precision")
                        .HasComment("Nhiệt độ cơ thể (°C)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo");

                    b.Property<bool>("HasAbnormalCry")
                        .HasColumnType("boolean")
                        .HasComment("Khóc bất thường");

                    b.Property<bool>("HasAbnormalHeartSound")
                        .HasColumnType("boolean")
                        .HasComment("Nghe tim bất thường");

                    b.Property<bool>("HasAbnormalTemperatureOrVitals")
                        .HasColumnType("boolean")
                        .HasComment("Nhiệt độ/sinh hiệu bất thường");

                    b.Property<bool>("HasAcuteOrChronicDisease")
                        .HasColumnType("boolean")
                        .HasComment("Bệnh cấp/mạn tính");

                    b.Property<bool>("HasHeartValveDisorder")
                        .HasColumnType("boolean")
                        .HasComment("Rối loạn van tim");

                    b.Property<bool>("HasImmunodeficiencyOrSuspectedHiv")
                        .HasColumnType("boolean")
                        .HasComment("Suy giảm miễn dịch hoặc nghi ngờ HIV");

                    b.Property<bool>("HasNeurologicalAbnormalities")
                        .HasColumnType("boolean")
                        .HasComment("Bất thường thần kinh");

                    b.Property<bool>("HasOtherContraindications")
                        .HasColumnType("boolean")
                        .HasComment("Chống chỉ định khác");

                    b.Property<bool>("HasPaleSkinOrLips")
                        .HasColumnType("boolean")
                        .HasComment("Da hoặc môi nhợt nhạt");

                    b.Property<bool>("HasPoorFeeding")
                        .HasColumnType("boolean")
                        .HasComment("Bú kém");

                    b.Property<bool>("HasSevereFeverAfterPreviousVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Sốt nặng sau tiêm trước");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsContraindicatedForVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Chống chỉ định");

                    b.Property<bool>("IsEligibleForVaccination")
                        .HasColumnType("boolean")
                        .HasComment("Đủ điều kiện tiêm");

                    b.Property<bool>("IsOnOrRecentlyEndedCorticosteroids")
                        .HasColumnType("boolean")
                        .HasComment("Đang/đã dùng corticosteroid");

                    b.Property<bool>("IsPretermBelow34Weeks")
                        .HasColumnType("boolean")
                        .HasComment("Sinh non < 34 tuần");

                    b.Property<bool>("IsReferredToHospital")
                        .HasColumnType("boolean")
                        .HasComment("Chuyển viện");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<bool>("IsUnderweightBelow2000g")
                        .HasColumnType("boolean")
                        .HasComment("Thiếu cân < 2000g");

                    b.Property<bool>("IsVaccinationDeferred")
                        .HasColumnType("boolean")
                        .HasComment("Tạm hoãn");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật");

                    b.Property<string>("ParentFullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Họ tên phụ huynh");

                    b.Property<string>("ParentPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Số điện thoại phụ huynh");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Khóa ngoại đến bảng tiếp nhận");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision")
                        .HasComment("Cân nặng (kg)");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ScreeningEvaluationReports_ReceptionId");

                    b.ToTable("ScreeningEvaluationReports", "public", t =>
                        {
                            t.HasComment("Bảng ghi nhận đánh giá sàng lọc trước tiêm");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày xuất hóa đơn");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NotPaid")
                        .HasComment("Trạng thái thanh toán");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("Số lượng");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer")
                        .HasComment("Mã tiếp nhận");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasComment("Số phiếu yêu cầu");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasComment("Mã dịch vụ");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServiceRequestDetails_ServiceId");

                    b.ToTable("ServiceRequestDetails", "public", t =>
                        {
                            t.HasComment("Bảng chi tiết yêu cầu dịch vụ");
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã loại dịch vụ");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Tên loại dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceTypes_Code");

                    b.ToTable("ServiceTypes", "public", t =>
                        {
                            t.HasComment("Loại hình dịch vụ tiếp nhận");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VAC001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            Name = "Tiêm chủng dịch vụ"
                        },
                        new
                        {
                            Id = 2,
                            Code = "VAC002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            Name = "Tiêm chủng đặc biệt"
                        },
                        new
                        {
                            Id = 3,
                            Code = "VAC003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            Name = "Tiêm chủng hợp đồng"
                        });
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("HasFeverAbove39")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasInjectionSiteReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOtherReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasReaction")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<string>("MedicineName")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("ObservationConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherReactionDescription")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PostVaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostVaccinationResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceptionVaccinationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionVaccinationId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ContractPatientVaccination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Contract", "Contract")
                        .WithMany("PlannedPatientVaccinations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.ReceptionVaccination", "ReceptionVaccination")
                        .WithOne()
                        .HasForeignKey("VaccinationReception.Domain.Models.ContractPatientVaccination", "ReceptionVaccinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");

                    b.Navigation("ReceptionVaccination");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ContractServiceDetail", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Contract", "Contract")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Examination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany()
                        .HasForeignKey("ReceptionId");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ExaminationTestResult", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Examination", "Examination")
                        .WithMany("ExaminationTestResults")
                        .HasForeignKey("ExaminationId");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Payment", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Payment", "OriginalPayment")
                        .WithMany()
                        .HasForeignKey("OriginalPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany("Payments")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalPayment");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.PaymentContract", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Contract", "Contract")
                        .WithMany("PaymentContracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.PaymentDetail", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Payment", "Payment")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.ReceptionVaccination", "ReceptionVaccination")
                        .WithMany()
                        .HasForeignKey("ReceptionVaccinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VaccinationReception.Domain.Models.ServiceRequestDetail", "ServiceRequestDetail")
                        .WithMany()
                        .HasForeignKey("ServiceRequestDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");

                    b.Navigation("ReceptionVaccination");

                    b.Navigation("ServiceRequestDetail");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Contract", "Contract")
                        .WithMany("Receptions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VaccinationReception.Domain.Models.ServiceType", "ServiceType")
                        .WithMany("Receptions")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ReceptionVaccination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany("ReceptionVaccinations")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationReception.Domain.Models.Reception", "SecondaryReception")
                        .WithMany("IncomingTransferredVaccinations")
                        .HasForeignKey("SecondaryReceptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Reception");

                    b.Navigation("SecondaryReception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ScreeningEvaluationReport", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithOne("ScreeningEvaluationReport")
                        .HasForeignKey("VaccinationReception.Domain.Models.ScreeningEvaluationReport", "ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceRequestDetail", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.Reception", "Reception")
                        .WithMany("ServiceRequestDetails")
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Vaccination", b =>
                {
                    b.HasOne("VaccinationReception.Domain.Models.ReceptionVaccination", "ReceptionVaccination")
                        .WithMany()
                        .HasForeignKey("ReceptionVaccinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceptionVaccination");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Contract", b =>
                {
                    b.Navigation("PaymentContracts");

                    b.Navigation("PlannedPatientVaccinations");

                    b.Navigation("Receptions");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Examination", b =>
                {
                    b.Navigation("ExaminationTestResults");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Payment", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.Reception", b =>
                {
                    b.Navigation("IncomingTransferredVaccinations");

                    b.Navigation("Payments");

                    b.Navigation("ReceptionVaccinations");

                    b.Navigation("ScreeningEvaluationReport");

                    b.Navigation("ServiceRequestDetails");
                });

            modelBuilder.Entity("VaccinationReception.Domain.Models.ServiceType", b =>
                {
                    b.Navigation("Receptions");
                });
#pragma warning restore 612, 618
        }
    }
}
