apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Database": "Server=postgres;Port=5432;Database=AuthenticationDb;User Id=postgres;Password=postgres;Include Error Detail=true;Pooling=true;MinPoolSize=5;MaxPoolSize=100;CommandTimeout=30;"
      },
      "GrpcSettings": {
        "HumanResourceUrl": "http://human-resource-grpc:80"
      },
      "Jwt": {
        "Secret": "super-duper-secret-value-that-should-be-in-user-secrets",
        "Issuer": "MediFlowIssuer",
        "Audience": "MediFlowAudience",
        "ExpirationInMinutes": 60
      }
    }
