apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: http
      targetPort: 8080
  type: {{ .Values.service.type }}