apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: http
      targetPort: 8080
    - protocol: TCP
      port: 443
      name: grpc
      targetPort: 8081
  type: {{ .Values.service.type }}