apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Database": "Server=Postgres;Port=5432;Database=InventoryDb;User Id=postgres;Password=postgres;Include Error Detail=true;Pooling=true;MinPoolSize=5;MaxPoolSize=100;CommandTimeout=30;"
      },
      "Jwt": {
        "Secret": "super-duper-secret-value-that-should-be-in-user-secrets",
        "Issuer": "MediFlowIssuer",
        "Audience": "MediFlowAudience",
        "ExpirationInMinutes": 60
      },
      "MessageBroker": {
        "Host": "amqp://rabbitmq:5672",
        "UserName": "mediflow",
        "Password": "Mediflow@123"
      },
      "ApprovalUrls": {
        "BaseUrl": "https://mediflow.health.vn",
        "ApprovalPath": "/pharmacy/expired-medicine/{0}/approval/callback?token={1}",
        "RejectionPath": "/pharmacy/expired-medicine/{0}/reject/callback?token={1}"
      },
      "GrpcSettings": {
        "CustomerInfoUrl": "https://customerinfo.grpc:8081",
        "HumanResourceUrl": "https://humanresource.grpc:8081"
      },
    }
