apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: inventory-service
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: "ddnhuy/inventory-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "120m"
              memory: "260Mi"
          env:
            - name: Kestrel__Endpoints__Http__Url
              value: "http://+:8080"
            - name: Kestrel__Endpoints__Https__Url
              value: "https://+:8081"
            - name: Kestrel__Endpoints__Https__Certificate__Path
              value: "/https/tls.crt"
            - name: Kestrel__Endpoints__Https__Certificate__KeyPath
              value: "/https/tls.key"
          envFrom:
            - configMapRef:
                name: inventory-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: tls-cert
              mountPath: /https
              readOnly: true
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      volumes:
        - name: config-volume
          configMap:
            name: inventory-config
            items:
              - key: appsettings.json
                path: appsettings.json
        - name: tls-cert
          secret:
            secretName: mediflow-internal-tls