apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-reception-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: vaccination-reception-service
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: vaccination-reception-service
    spec:
      containers:
        - name: vaccination-reception-service
          image: "ddnhuy/vaccinationreception-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "150m"
              memory: "260Mi"
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/https/tls.crt"
            - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
              value: "/https/tls.key"
            - name: PayOS__ClientId
              valueFrom:
                secretKeyRef:
                  name: pay-os-secret
                  key: PAYOS_CLIENT_ID
            - name: PayOS__ApiKey
              valueFrom:
                secretKeyRef:
                  name: pay-os-secret
                  key: PAYOS_CLIENT_API_KEY
            - name: PayOS__ChecksumKey
              valueFrom:
                secretKeyRef:
                  name: pay-os-secret
                  key: PAYOS_CHECKSUM_KEY
            - name: PayOS__CancelUrl
              valueFrom:
                secretKeyRef:
                  name: pay-os-secret
                  key: PAYOS_CANCEL_URL
            - name: PayOS__ReturnUrl
              valueFrom:
                secretKeyRef:
                  name: pay-os-secret
                  key: PAYOS_RETURN_URL
          envFrom:
            - configMapRef:
                name: vaccination-reception-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: tls-cert
              mountPath: /https
              readOnly: true
      initContainers:
        - name: wait-for-customer-info-grpc
          image: busybox
          command: ['sh', '-c', "until nc -z customer-info-grpc {{ .Values.service.port }}; do echo waiting for customer-info-grpc; sleep 2; done"]
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done']
      volumes:
        - name: config-volume
          configMap:
            name: vaccination-reception-config
            items:
              - key: appsettings.json
                path: appsettings.json
        - name: tls-cert
          secret:
            secretName: mediflow-internal-tls