apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-reception-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: vaccination-reception-service
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: vaccination-reception-service
    spec:
      containers:
        - name: vaccination-reception-service
          image: "ddnhuy/vaccinationreception-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: vaccination-reception-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      initContainers:
        - name: wait-for-customer-info-grpc
          image: busybox
          command: ['sh', '-c', "until nc -z customer-info-grpc {{ .Values.service.port }}; do echo waiting for customer-info-grpc; sleep 2; done"]
      volumes:
        - name: config-volume
          configMap:
            name: vaccination-reception-config
            items:
              - key: appsettings.json
                path: appsettings.json