// <auto-generated />
using System;
using HospitalService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624030617_AddFilteredUniqueIndexToServiceGroupServices")]
    partial class AddFilteredUniqueIndexToServiceGroupServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalService.Domain.Models.DiseaseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Mô tả nhóm bệnh");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Tên nhóm bệnh");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("IX_DiseaseGroups_GroupName");

                    b.ToTable("DiseaseGroups", "public", t =>
                        {
                            t.HasComment("Bảng nhóm bệnh");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Các bệnh có khả năng lây truyền từ người sang người",
                            GroupName = "Nhóm bệnh truyền nhiễm",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Description = "Các bệnh không có khả năng lây truyền",
                            GroupName = "Nhóm bệnh không truyền nhiễm",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("HospitalService.Domain.Models.DiseaseGroupService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<int>("DiseaseGroupId")
                        .HasColumnType("integer")
                        .HasComment("Mã nhóm bệnh");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasComment("Mã dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseGroupId")
                        .HasDatabaseName("IX_DiseaseGroupServices_DiseaseGroupId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_DiseaseGroupServices_ServiceId");

                    b.HasIndex("DiseaseGroupId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("IX_DiseaseGroupServices_DiseaseGroupId_ServiceId")
                        .HasFilter("\"IsCancelled\" = false");

                    b.ToTable("DiseaseGroupServices", "public", t =>
                        {
                            t.HasComment("Bảng liên kết nhóm bệnh và dịch vụ");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DiseaseGroupId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DiseaseGroupId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("HospitalService.Domain.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasComment("Mã phòng ban");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Mã dịch vụ");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Tên dịch vụ");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Đơn giá");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Services_DepartmentId");

                    b.HasIndex("ServiceCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Services_ServiceCode");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("IX_Services_ServiceName");

                    b.ToTable("Services", "public", t =>
                        {
                            t.HasComment("Bảng dịch vụ");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DepartmentId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceCode = "VAC001",
                            ServiceName = "Tiêm vắc xin 5 trong 1",
                            UnitPrice = 500000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            DepartmentId = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceCode = "VAC002",
                            ServiceName = "Tiêm vắc xin 6 trong 1",
                            UnitPrice = 600000m
                        });
                });

            modelBuilder.Entity("HospitalService.Domain.Models.ServiceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Tên nhóm dịch vụ");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("IX_ServiceGroups_GroupName");

                    b.ToTable("ServiceGroups", "public", t =>
                        {
                            t.HasComment("Bảng nhóm dịch vụ");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            GroupName = "Nhóm dịch vụ tiêm chủng cơ bản",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            GroupName = "Nhóm dịch vụ tiêm chủng đặc biệt",
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("HospitalService.Domain.Models.ServiceGroupService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key")
                        .HasAnnotation("Npgsql:IdentityIncrement", 1)
                        .HasAnnotation("Npgsql:IdentityStartValue", 1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày tạo bản ghi");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người tạo bản ghi");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái hủy");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái tạm ngưng");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ngày cập nhật bản ghi cuối cùng");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("integer")
                        .HasComment("Người cập nhật bản ghi cuối cùng");

                    b.Property<int>("ServiceGroupId")
                        .HasColumnType("integer")
                        .HasComment("Mã nhóm dịch vụ");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasComment("Mã dịch vụ");

                    b.HasKey("Id");

                    b.HasIndex("ServiceGroupId")
                        .HasDatabaseName("IX_ServiceGroupServices_ServiceGroupId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_ServiceGroupServices_ServiceId");

                    b.HasIndex("ServiceGroupId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceGroupServices_ServiceGroupId_ServiceId")
                        .HasFilter("\"IsCancelled\" = false");

                    b.ToTable("ServiceGroupServices", "public", t =>
                        {
                            t.HasComment("Bảng liên kết nhóm dịch vụ và dịch vụ");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceGroupId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsCancelled = false,
                            IsSuspended = false,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedBy = 1,
                            ServiceGroupId = 2,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("HospitalService.Domain.Models.DiseaseGroupService", b =>
                {
                    b.HasOne("HospitalService.Domain.Models.DiseaseGroup", "DiseaseGroup")
                        .WithMany("DiseaseGroupServices")
                        .HasForeignKey("DiseaseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalService.Domain.Models.Service", "Service")
                        .WithMany("DiseaseGroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiseaseGroup");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HospitalService.Domain.Models.ServiceGroupService", b =>
                {
                    b.HasOne("HospitalService.Domain.Models.ServiceGroup", "ServiceGroup")
                        .WithMany("ServiceGroupServices")
                        .HasForeignKey("ServiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalService.Domain.Models.Service", "Service")
                        .WithMany("ServiceGroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceGroup");
                });

            modelBuilder.Entity("HospitalService.Domain.Models.DiseaseGroup", b =>
                {
                    b.Navigation("DiseaseGroupServices");
                });

            modelBuilder.Entity("HospitalService.Domain.Models.Service", b =>
                {
                    b.Navigation("DiseaseGroupServices");

                    b.Navigation("ServiceGroupServices");
                });

            modelBuilder.Entity("HospitalService.Domain.Models.ServiceGroup", b =>
                {
                    b.Navigation("ServiceGroupServices");
                });
#pragma warning restore 612, 618
        }
    }
}
