apiVersion: v1
kind: ConfigMap
metadata:
  name: management-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "GrpcSettings": {
        "HumanResourceUrl": "http://human-resource-grpc:80",
        "InventoryUrl": "http://inventory-service:443",
        "VaccinationReceptionUrl": "http://vaccination-reception-service:443"
      },
      "Jwt": {
        "Secret": "super-duper-secret-value-that-should-be-in-user-secrets",
        "Issuer": "MediFlowIssuer",
        "Audience": "MediFlowAudience",
        "ExpirationInMinutes": 60
      }
    }
