apiVersion: v1
kind: Service
metadata:
  name: seq
spec:
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: web
      targetPort: 80
    - protocol: TCP
      port: 5341
      name: ingestion
      targetPort: 5341
  type: {{ .Values.service.type }}