namespace BuildingBlocks.Strings
{
    public enum ExceptionKey
    {
        REQUIRED_QUANTITY,
        INVALID_QUANTITY,
        INVALID_DEFAULT_QUANTITY,

        REQUIRED_APPOINTMENT_DATE,
        INVALID_APPOINTMENT_DATE,

        INVALID_WEIGHT,
        INVALID_TEMPERATURE,
        INVALID_BLOOD_PRESSURE_SYSTOLIC,
        INVALID_BLOOD_PRESSURE_DIASTOLIC,

        #region HumanResource Exceptions
        // User related
        NOT_FOUND_USER_WITH_ID,
        NOT_FOUND_USER_WITH_EMAIL,
        INVALID_LOGIN_CREDENTIAL,
        FAILED_UPDATE_USER_WITH_ID,
        FAILED_RESET_PASSWORD,
        FAILED_CHANGE_PASSWORD,
        FAILED_ASSIGN_ROLE_TO_USER,

        // Role / Department / Permission
        NOT_FOUND_ROLE_WITH_ID,
        NOT_FOUND_DEPARTMENT_WITH_ID,
        NOT_FOUND_PERMISSION_WITH_ID,
        FAILED_DELETE_DEPARTMENT,
        FAILED_DELETE_USER,

        // Policy
        NOT_FOUND_POLICY_WITH_ID,
        CANNOT_DELETE_POLICY_WITH_RELATIONSHIPS,
        POLICY_ASSIGNMENT_ALREADY_EXISTS,

        // Department
        EXISTED_DEPARTMENT_CODE,

        // Generic
        INVALID_REQUEST,
        INVALID_DEPARTMENT_TYPE,
        #endregion

        #region Inventory Exceptions
        // Warehouse
        NOT_FOUND_WAREHOUSE_WITH_ID,
        NOT_FOUND_WAREHOUSE_WITH_CODE,
        FAILED_UPDATE_WAREHOUSE_WITH_ID,
        FAILED_DELETE_WAREHOUSE_WITH_ID,
        DUPLICATE_WAREHOUSE_CODE,

        // Warehouse type
        NOT_FOUND_WAREHOUSE_TYPE_WITH_ID,
        NOT_FOUND_WAREHOUSE_TYPE_WITH_CODE,

        // Supplier
        NOT_FOUND_SUPPLIER_WITH_ID,
        NOT_FOUND_SUPPLIER_WITH_CODE,
        FAILED_CREATE_SUPPLIER_WITH_ID,
        FAILED_UPDATE_SUPPLIER_WITH_ID,
        FAILED_DELETE_SUPPLIER_WITH_ID,
        DUPLICATE_SUPPLIER_CODE,

        // Medicine
        NOT_FOUND_MEDICINE_WITH_ID,
        NOT_FOUND_MEDICINE_WITH_CODE,
        NOT_FOUND_MEDICINE_WITH_NAME,
        FAILED_CREATE_MEDICINE,
        FAILED_UPDATE_MEDICINE_WITH_ID,
        FAILED_DELETE_MEDICINE_WITH_ID,
        DUPLICATE_MEDICINE_CODE,
        MEDICINE_EXPIRED,
        MEDICINE_NEAR_EXPIRY,

        // Medicine interaction
        INCOMPATIBLE_MEDICINES,
        INTERACTION_ALREADY_EXISTS,
        FAILED_UPDATE_INTERACTION_WITH_ID,
        FAILED_DELETE_INTERACTION_WITH_ID,
        INVALID_INTERACTION_SEVERITY,
        NOT_FOUND_INTERACTION_WITH_ID,

        // General inventory
        INVALID_INVENTORY_OPERATION,
        INSUFFICIENT_STOCK,
        DUPLICATE_DOCUMENT,

        // Document
        FAILED_GENERATE_DOCUMENT_CODE,

        // Length
        INVALID_MEDICINE_CODE_MAX_LENGTH,
        INVALID_MEDICINE_NAME_MAX_LENGTH,
        INVALID_MEDICINE_UNIT_MAX_LENGTH,
        INVALID_ACTIVE_INGREDIENT_MAX_LENGTH,
        INVALID_USAGE_INSTRUCTIONS_MAX_LENGTH,
        INVALID_CONCENTRATION_MAX_LENGTH,
        INVALID_INDICATIONS_MAX_LENGTH,
        INVALID_MEDICINE_CLASSIFICATION_MAX_LENGTH,
        INVALID_ROUTE_OF_ADMINISTRATION_MAX_LENGTH,
        INVALID_NATIONAL_MEDICINE_CODE_MAX_LENGTH,
        INVALID_REGISTRATION_NUMBER_MAX_LENGTH,
        INVALID_MEDICINE_DESCRIPTION_MAX_LENGTH,
        INVALID_MEDICINE_NOTE_MAX_LENGTH,
        #endregion

        #region VaccinationReception Exceptions
        NOT_FOUND_PATIENT_WITH_ID,
        INVALID_VACCINATION_RECEPTION_ID,
        INVALID_VACCINATION_RECEPTION_ID_LIST,
        FAILED_DELETE_VACCINATION_RECEPTION,
        NOT_FOUND_VACCINATION_RECEPTION_WITH_ID,
        NOT_FOUND_UNPAID_SERVICES_WITH_RECEPTION_ID,

        // Patient
        REQUIRED_PATIENT_INFO,
        REQUIRED_PATIENT_CODE,
        INVALID_PATIENT_CODE_MAX_LENGTH,
        REQUIRED_PATIENT_NAME,
        INVALID_PATIENT_NAME_MAX_LENGTH,
        REQUIRED_PATIENT_GENDER,
        INVALID_PATIENT_GENDER,
        REQUIRED_PATIENT_DOB,
        INVALID_PATIENT_DOB,
        REQUIRED_PATIENT_PHONE,
        INVALID_PATIENT_PHONE_FORMAT,
        INVALID_PATIENT_PHONE_MAX_LENGTH,
        REQUIRED_PATIENT_IDENTITY_CARD,
        INVALID_PATIENT_IDENTITY_CARD_FORMAT,
        INVALID_PATIENT_IDENTITY_CARD_MAX_LENGTH,
        REQUIRED_PATIENT_ADDRESS_DETAIL,
        INVALID_PATIENT_ADDRESS_MAX_LENGTH,
        REQUIRED_PATIENT_PROVINCE,
        INVALID_PATIENT_PROVINCE_MAX_LENGTH,
        REQUIRED_PATIENT_DISTRICT,
        INVALID_PATIENT_DISTRICT_MAX_LENGTH,
        REQUIRED_PATIENT_WARD,
        INVALID_PATIENT_WARD_MAX_LENGTH,
        PATIENT_CODE_EXISTS,
        FAILED_CREATE_PATIENT,
        FAILED_UPDATE_PATIENT,
        FAILED_DELETE_PATIENT,

        // Vaccination Reception
        REQUIRED_VACCINATION_RECEPTION_INFO,
        INVALID_GROUP_ID,
        INVALID_GROUP_TYPE,
        INVALID_DATA,
        REQUIRED_VACCINATION_RECEPTION_ID,
        REQUIRED_VACCINATION_RECEPTION_DATE,
        INVALID_VACCINATION_RECEPTION_DATE,
        INVALID_SERVICE_TYPE,
        REQUIRED_SCHEDULED_DATE,
        INVALID_SCHEDULED_DATE,
        INVALID_DOCTOR_ID,
        INVALID_NOTE_MAX_LENGTH,
        INVALID_TEST_RESULT_ENTRY_MAX_LENGTH,
        INVALID_DATA_FOLLOWING_BUSINESS_RULES,

        // Request Form
        NOT_FOUND_REQUEST_FORM_WITH_RECEPTION_ID,
        INVALID_REQUEST_FORM_ID,
        INVALID_SERVICE_LIST,

        // Service Request
        NOT_FOUND_SERVICE_REQUEST,

        // Vaccine
        INVALID_VACCINE_ID,

        // Screening Evaluation Report
        INVALID_PARENT_FULL_NAME_MAX_LENGTH,
        INVALID_PARENT_PHONE_FORMAT,
        INVALID_TEST_RESULT,
        INVALID_TEST_RESULT_FOLLOWING_CONTRAINDICATIONS,
        #endregion

        #region HospitalService Exceptions
        // Service
        FAILED_CREATE_SERVICE,
        SERVICE_NOT_FOUND,
        FAILED_DELETE_SERVICE,
        FAILED_UPDATE_SERVICE,
        INVALID_SERVICE_ID,

        // Service Group
        SERVICE_GROUP_NOT_FOUND,
        FAILED_ADD_SERVICES_TO_GROUP,
        EMPTY_SERVICE_IDS,
        INVALID_SERVICE_GROUP_ID,
        FAILED_REMOVE_SERVICES_FROM_GROUP,
        FAILED_UPDATE_SERVICE_GROUP,
        EMPTY_GROUP_NAME,
        FAILED_DELETE_SERVICE_GROUP,
        FAILED_CREATE_SERVICE_GROUP,

        // Disease Group
        INVALID_DISEASE_GROUP_ID,
        FAILED_DELETE_DISEASE_GROUP,
        EMPTY_DISEASE_GROUP_NAME,
        FAILED_UPDATE_DISEASE_GROUP,
        FAILED_ADD_SERVICES_TO_DISEASE_GROUP,
        FAILED_REMOVE_SERVICES_FROM_DISEASE_GROUP,
        DISEASE_GROUP_NOT_FOUND,
        FAILED_CREATE_DISEASE_GROUP,
        #endregion

        #region FileStorage Exceptions
        UPLOAD_FAILED,
        FILE_NOT_FOUND,
        #endregion

        #region Appointment Exceptions
        NOT_FOUND_APPOINTMENT_WITH_ID,
        NOT_FOUND_APPOINTMENT_WITH_PATIENT_ID,
        NOT_FOUND_APPOINTMENT_WITH_DATE,
        #endregion

        #region Validation Exceptions
        // User validation
        REQUIRED_USERNAME,
        REQUIRED_PASSWORD,
        INVALID_PASSWORD_LENGTH,
        INVALID_NEW_PASSWORD,
        REQUIRED_REFRESH_TOKEN,
        INVALID_REFRESH_TOKEN,
        REQUIRED_USER_ID,
        REQUIRED_CURRENT_PASSWORD,
        REQUIRED_NEW_PASSWORD,
        REQUIRED_EMAIL,
        INVALID_EMAIL,
        REQUIRED_NAME,
        REQUIRED_PHONE,
        REQUIRED_CODE,
        REQUIRED_ADDRESS,
        REQUIRED_PROFILE_PICTURE_URL,
        REQUIRED_ROLE,
        REQUIRED_DEPARTMENT_IDS,
        INVALID_USER_DATA,

        // Department validation
        REQUIRED_DEPARTMENT_ID,
        REQUIRED_DEPARTMENT_CODE,
        REQUIRED_DEPARTMENT_NAME,
        REQUIRED_DEPARTMENT_NAME_IN_ENGLISH,
        REQUIRED_DEPARTMENT_TYPE,

        // Warehouse validation
        REQUIRED_WAREHOUSE_CODE,
        REQUIRED_WAREHOUSE_NAME,
        INVALID_WAREHOUSE_CODE_FORMAT,
        REQUIRED_WAREHOUSE_TYPE,
        INVALID_WAREHOUSE_TYPE,

        // Supplier validation
        REQUIRED_SUPPLIER_CODE,
        REQUIRED_SUPPLIER_NAME,
        REQUIRED_SUPPLIER_ADDRESS,
        REQUIRED_SUPPLIER_CONTACT_PERSON,
        REQUIRED_SUPPLIER_DIRECTOR,
        REQUIRED_SUPPLIER_FAX,
        INVALID_SUPPLIER_CODE_FORMAT,
        INVALID_SUPPLIER_PHONE,
        INVALID_SUPPLIER_EMAIL,
        INVALID_SUPPLIER_TAX_CODE,

        // Medicine validation
        REQUIRED_MEDICINE_CODE,
        REQUIRED_MEDICINE_NAME,
        INVALID_MEDICINE_CODE_FORMAT,
        REQUIRED_MEDICINE_UNIT,
        REQUIRED_MEDICINE_CATEGORY,
        INVALID_MEDICINE_PRICE,
        INVALID_MEDICINE_QUANTITY,
        INVALID_MEDICINE_EXPIRY_DATE,
        INVALID_MEDICINE_MANUFACTURE_DATE,
        INVALID_DATE_RANGE,
        REQUIRED_MEDICINE_ROUTE,
        REQUIRED_MEDICINE_DOSAGE_FORM,
        REQUIRED_MANUFACTURER,
        REQUIRED_ACTIVE_INGREDIENT,
        REQUIRED_USAGE_INSTRUCTIONS,
        REQUIRED_CONCENTRATION,
        REQUIRED_INDICATIONS,
        REQUIRED_MEDICINE_CLASSIFICATION,
        REQUIRED_ROUTE_OF_ADMINISTRATION,
        REQUIRED_NATIONAL_MEDICINE_CODE,
        REQUIRED_REGISTRATION_NUMBER,
        REQUIRED_VALID_MEDICINE_TYPE,
        REQUIRED_VALID_VACCINE_TYPE,
        REQUIRED_IS_REQUIRED_TESTING_BEFORE_USE,

        // Medicine interaction validation
        REQUIRED_FIRST_MEDICINE,
        REQUIRED_SECOND_MEDICINE,
        SAME_MEDICINE_INTERACTION,
        REQUIRED_INTERACTION_SEVERITY,
        REQUIRED_INTERACTION_EFFECT,
        INVALID_SEVERITY_LEVEL,

        // Medicine price validation
        REQUIRED_MEDICINE_PRICE_ID,
        INVALID_MEDICINE_PRICE_ID,
        REQUIRED_UNIT_PRICE,
        INVALID_UNIT_PRICE,
        REQUIRED_CURRENCY,
        INVALID_CURRENCY_FORMAT,
        REQUIRED_VAT_RATE,
        INVALID_VAT_RATE,
        REQUIRED_VAT_AMOUNT,
        INVALID_VAT_AMOUNT,
        REQUIRED_PRICE_BEFORE_VAT,
        INVALID_PRICE_BEFORE_VAT,
        REQUIRED_PRICE_AFTER_VAT,
        INVALID_PRICE_AFTER_VAT,
        NOT_FOUND_MEDICINE_PRICE,

        // Inventory operation validation
        REQUIRED_OPERATION_DATE,
        INVALID_OPERATION_DATE,
        REQUIRED_OPERATION_TYPE,
        REQUIRED_SOURCE_WAREHOUSE,
        REQUIRED_DESTINATION_WAREHOUSE,
        SAME_WAREHOUSE_TRANSFER,

        // Import medicine validation
        REQUIRED_WAREHOUSE_ID,
        REQUIRED_SUPPLIER_ID,
        REQUIRED_RECEIVER_ID,
        REQUIRED_DOCUMENT_CODE,
        REQUIRED_DOCUMENT_NUMBER,
        REQUIRED_IMPORT_DATE,
        REQUIRED_MEDICINE_DETAIL,
        REQUIRED_MEDICINE_ID,
        REQUIRED_BATCH_NUMBER,
        QUANTITY_GREATER_THAN_ZERO,
        UNIT_PRICE_NON_NEGATIVE,
        REQUIRED_EXPIRY_DATE,
        EXPIRY_DATE_FUTURE,
        REQUIRED_MANUFACTURER_ID,
        REQUIRED_COUNTRY_ID,

        // Pagination validation
        PAGE_SIZE_TOO_SMALL,
        PAGE_SIZE_TOO_LARGE,
        PAGE_INDEX_TOO_SMALL,
        PAGE_INDEX_TOO_LARGE,

        // File Storage validation
        FILE_NOT_PROVIDED,
        FILE_TOO_LARGE,
        INVALID_IMAGE_FORMAT,
        INVALID_PUBLIC_ID,
        FOLDER_NAME_TOO_LONG,
        INVALID_IMAGE_URL,
        REQUIRED_FILE_NAME,
        REQUIRED_FILE_TYPE,
        INVALID_FILE_TYPE,
        INVALID_FILE_ID,

        // Service validation
        REQUIRED_SERVICE_CODE,
        SERVICE_CODE_MAX_LENGTH,
        INVALID_SERVICE_CODE_FORMAT,
        REQUIRED_SERVICE_NAME,
        SERVICE_NAME_MAX_LENGTH,
        SERVICE_NAME_MIN_LENGTH,
        INVALID_SERVICE_PRICE,
        SERVICE_PRICE_TOO_LARGE,

        // ServiceGroup validation
        REQUIRED_GROUP_NAME,
        GROUP_NAME_MAX_LENGTH,
        GROUP_NAME_MIN_LENGTH,

        // DiseaseGroup validation
        REQUIRED_DISEASE_GROUP_NAME,
        DISEASE_GROUP_NAME_MAX_LENGTH,
        DISEASE_GROUP_NAME_MIN_LENGTH,
        DISEASE_GROUP_DESCRIPTION_MAX_LENGTH,

        // Appointment validation
        REQUIRED_APPOINTMENT_ID,
        REQUIRED_PATIENT_ID,
        INVALID_PATIENT_ID,
        REQUIRED_APPOINTMENT_TYPE,
        INVALID_APPOINTMENT_TYPE,
        REQUIRED_PATIENT_EMAIL,
        INVALID_PATIENT_EMAIL,
        INVALID_PATIENT_PHONE_NUMBER,
        REQUIRED_SUSPENDED_STATUS,
        #endregion

        #region HospitalFee Exceptions
        ONE_OR_MORE_ITEMS_ALREADY_PAID_OR_INVALID,
        CANCEL_ITEMS_NOT_PAID_OR_INVALID,
        ORIGINAL_PAYMENT_NOT_FOUND_FOR_RECEPTION,
        REFUNDED_ITEMS_NOT_PAID_OR_INVALID,
        REFUND_AMOUNT_MUST_BE_NEGATIVE,
        #endregion

        INVALID_SERVICE_IDS,
        NOT_FOUND_VACCINATION_WITH_ID,
        HOSPITAL_SERVICE_UNAVAILABLE,
        UNEXPECTED_ERROR_WHILE_CALLING_HOSPITAL_SERVICE,
        UNEXPECTED_ERROR_WHILE_CALLING_INVENTORY_SERVICE,
        PAYMENT_NOT_FOUND,
        PAYMENT_ID_INVALID,
        NOT_FOUND_RECEPTION_WITH_ID,
        NOT_FOUND_UNPAID_SERVICES_WITH_PATIENT_ID
    }
}
