syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "HumanResource.Grpc";

package department;

// ---------- gRPC Service ----------
service DepartmentProtoService {
  rpc ListDepartments (ListDepartmentsRequest) returns (ListDepartmentsResponse);
  rpc GetDepartment (GetDepartmentRequest) returns (DepartmentDetailModel);
  rpc CreateDepartment (CreateDepartmentRequest) returns (DepartmentDetailModel);
  rpc UpdateDepartment (UpdateDepartmentRequest) returns (DepartmentDetailModel);
  rpc DeleteDepartment (DeleteDepartmentRequest) returns (DeleteDepartmentResponse);
  
  rpc ListEmployees (ListEmployeesRequest) returns (ListEmployeesResponse);
}

// ---------- Request & Response ----------
message ListDepartmentsRequest {
  int32 pageIndex = 1;
  int32 pageSize = 2;
  string keyword = 3;
}

message ListDepartmentsResponse {
  int32 pageIndex = 1;
  int32 pageSize = 2;
  int32 count = 3;
  repeated DepartmentSummaryModel data = 4;
}

message GetDepartmentRequest {
  int32 id = 1;
}

message CreateDepartmentRequest {
  string code = 1;
  string name = 2;
  string nameInEnglish = 3;
  int32 departmentTypeId = 4;
}

message UpdateDepartmentRequest {
  int32 id = 1;
  string code = 2;
  string name = 3;
  string nameInEnglish = 4;
  int32 departmentTypeId = 5;
  bool isSuspended = 6;
  bool isCancelled = 7;
}

message DeleteDepartmentRequest {
  int32 id = 1;
}

message DeleteDepartmentResponse {
  bool isSuccess = 1;
}

message ListEmployeesRequest {
  int32 pageIndex = 1;
  int32 pageSize = 2;
  int32 id = 3;
}

message ListEmployeesResponse {
  int32 pageIndex = 1;
  int32 pageSize = 2;
  int32 count = 3;
  repeated EmployeeSummaryModel data = 4;
}

// ---------- Data Models ----------
message DepartmentSummaryModel {
  int32 id = 1;
  string code = 2;
  string name = 3;
  string nameInEnglish = 4;
  string departmentTypeName = 5;
  string departmentTypeNameInEnglish = 6;
  bool isSuspended = 7;
}

message DepartmentDetailModel {
  int32 id = 1;
  string code = 2;
  string name = 3;
  string nameInEnglish = 4;
  int32 departmentTypeId = 5;
  string departmentTypeName = 6;
  string departmentTypeNameInEnglish = 7;
  bool isSuspended = 8;
  bool isCancelled = 9;
  google.protobuf.Timestamp createdAt = 10;
  int32 createdBy = 11;
  google.protobuf.Timestamp lastUpdatedAt = 12;
  int32 lastUpdatedBy = 13;
}

message EmployeeSummaryModel {
  int32 id = 1;
  string code = 2;
  string name = 3;
  bool isSuspended = 4;
  string profilePictureUrl = 5;
}