syntax = "proto3";

option csharp_namespace = "HumanResource.Grpc";

package department_type;

// ---------- gRPC Service ----------
service DepartmentTypeProtoService {
  rpc ListDepartmentTypes (ListDepartmentTypesRequest) returns (ListDepartmentTypesResponse);
}

// ---------- Request & Response ----------
message ListDepartmentTypesRequest {
}

message ListDepartmentTypesResponse {
  repeated DepartmentTypeModel data = 1;
}


// ---------- Data Models ----------
message DepartmentTypeModel {
  int32 id = 1;
  string code = 2;
  string name = 3;
  string nameInEnglish = 4;
}